name: acidwarp # you probably want to 'snapcraft register <name>'
base: core24 # the base snap is the execution environment for this snap
version: '1.0.0+1' # just for humans, typically '1.2+git' or '1.3.2'
summary: It's eye-candy — watch the pretty colors! # 79 char long summary
description: |
  Acid Warp is software that falls into the category of "eye-candy". It
  generates soft, friendly pictures on your screen. It selects from over
  40 mathematical function to generate each picture pattern. Once displayed
  the colors of each picture are animated to produce a flowing and moving
  picture.  Source code: https://github.com/Dermochelys/acidwarp-linux

title: Acid Warp
license: GPL-3.0
source-code: https://github.com/Dermochelys/acidwarp-linux
issues: https://github.com/Dermochelys/acidwarp-linux/issues

platforms:
  amd64:

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

icon: snap/icon.png

apps:
  acidwarp:
    command: usr/bin/acidwarp-linux
    desktop: usr/share/applications/acidwarp.desktop
    plugs:
      - x11
      - wayland
      - opengl
      - desktop
      - desktop-legacy

parts:
  sdl3:
    plugin: cmake
    source: https://github.com/libsdl-org/SDL.git
    source-tag: release-3.2.24
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DSDL_STATIC=ON
      - -DSDL_SHARED=OFF
      - -DCMAKE_POSITION_INDEPENDENT_CODE=ON
      - -DCMAKE_INSTALL_PREFIX=/usr
    build-packages:
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libwayland-dev
      - libxkbcommon-dev
      - libegl1-mesa-dev
      - libdrm-dev
      - libgbm-dev
      - libx11-dev
      - libxext-dev
      - libxrandr-dev
      - libxcursor-dev
      - libxi-dev
      - libxinerama-dev
      - libxxf86vm-dev
      - libxss-dev
      - wayland-protocols

  acidwarp:
    after: [sdl3]
    plugin: cmake
    source: https://github.com/Dermochelys/acidwarp-linux.git
    source-type: git
    build-packages:
      - libgl1-mesa-dev
      - cmake
    stage-packages:
      - libgl1
      - libglx0
      - libglvnd0
      - libopengl0
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_PREFIX_PATH=$CRAFT_STAGE/usr
